export function mapModalityToSport(modality: string): string {
  const mapping: Record<string, string> = {
    // Mapeamento em português
    Futebol: 'soccer',
    Motorsport: 'motorsport',
    Lutas: 'fighting',
    Beisebol: 'baseball',
    Basquete: 'basketball',
    'Futebol Americano': 'american football',
    'Hóquei no Gelo': 'ice hockey',
    Golfe: 'golf',
    Rúgbi: 'rugby',
    Tênis: 'tennis',
    Críquete: 'cricket',
    Ciclismo: 'cycling',
    'Futebol Australiano': 'australian football',
    ESports: 'esports',
    Vôlei: 'volleyball',
    Netball: 'netball',
    Handebol: 'handball',
    Sinuca: 'snooker',
    'Hóquei na Grama': 'field hockey',
    Dardos: 'darts',
    Atletismo: 'athletics',
    Badminton: 'badminton',
    Escalada: 'climbing',
    Equitação: 'equestrian',
    Ginástica: 'gymnastics',
    'Tiro Esportivo': 'shooting',
    'Esportes Radicais': 'extreme sports',
    'Tênis de Mesa': 'table tennis',
    Multiesportivos: 'multi sports',
    'Esportes Aquáticos': 'watersports',
    'Levantamento de Peso': 'weightlifting',
    Esqui: 'skiing',
    Patinação: 'skating',
    'Esportes de Inverno': 'wintersports',
    Lacrosse: 'lacrosse',
    Apostas: 'gambling',
    'Esportes Gaélicos': 'gaelic',

    // Mapeamento em inglês como fallback
    Soccer: 'soccer',
    Fighting: 'fighting',
    Baseball: 'baseball',
    Basketball: 'basketball',
    'American Football': 'american football',
    'Ice Hockey': 'ice hockey',
    Golf: 'golf',
    Rugby: 'rugby',
    Tennis: 'tennis',
    Cricket: 'cricket',
    Cycling: 'cycling',
    'Australian Football': 'australian football',
    Volleyball: 'volleyball',
    Handball: 'handball',
    Snooker: 'snooker',
    'Field Hockey': 'field hockey',
    Darts: 'darts',
    Athletics: 'athletics',
    Climbing: 'climbing',
    Equestrian: 'equestrian',
    Gymnastics: 'gymnastics',
    Shooting: 'shooting',
    'Extreme Sports': 'extreme sports',
    'Table Tennis': 'table tennis',
    'Multi Sports': 'multi sports',
    Watersports: 'watersports',
    Weightlifting: 'weightlifting',
    Skiing: 'skiing',
    Skating: 'skating',
    Wintersports: 'wintersports',
    Gambling: 'gambling',
    Gaelic: 'gaelic',
  };

  return mapping[modality] || modality.toLowerCase();
}
