export const COUNTRY_TIMEZONES: Record<string, string> = {
  // Países da sua lista original
  Vietnam: 'Asia/Ho_Chi_Minh',
  Brazil: 'America/Sao_Paulo',
  England: 'Europe/London',
  USA: 'America/New_York',
  Spain: 'Europe/Madrid',
  Germany: 'Europe/Berlin',
  France: 'Europe/Paris',
  Italy: 'Europe/Rome',
  Portugal: 'Europe/Lisbon',
  Argentina: 'America/Argentina/Buenos_Aires',
  Mexico: 'America/Mexico_City',
  Japan: 'Asia/Tokyo',
  China: 'Asia/Shanghai',
  India: 'Asia/Kolkata',
  Australia: 'Australia/Sydney',

  // Todos os outros países da sua lista completa
  Andorra: 'Europe/Andorra',
  'United Arab Emirates': 'Asia/Dubai',
  Afghanistan: 'Asia/Kabul',
  'Antigua and Barbuda': 'America/Antigua',
  Anguilla: 'America/Anguilla',
  Albania: 'Europe/Tirane',
  Armenia: 'Asia/Yerevan',
  Angola: 'Africa/Luanda',
  Antarctica: 'Antarctica/McMurdo',
  'American Samoa': 'Pacific/Pago_Pago',
  Austria: 'Europe/Vienna',
  Aruba: 'America/Aruba',
  Aland: 'Europe/Mariehamn',
  Azerbaijan: 'Asia/Baku',
  'Bosnia and Herzegovina': 'Europe/Sarajevo',
  Barbados: 'America/Barbados',
  Bangladesh: 'Asia/Dhaka',
  Belgium: 'Europe/Brussels',
  'Burkina Faso': 'Africa/Ouagadougou',
  Bulgaria: 'Europe/Sofia',
  Bahrain: 'Asia/Bahrain',
  Burundi: 'Africa/Bujumbura',
  Benin: 'Africa/Porto-Novo',
  'Saint Barthelemy': 'America/St_Barthelemy',
  Bermuda: 'Atlantic/Bermuda',
  Brunei: 'Asia/Brunei',
  Bolivia: 'America/La_Paz',
  Bonaire: 'America/Kralendijk',
  Bahamas: 'America/Nassau',
  Bhutan: 'Asia/Thimphu',
  'Bouvet Island': 'Antarctica/Bouvet',
  Botswana: 'Africa/Gaborone',
  Belarus: 'Europe/Minsk',
  Belize: 'America/Belize',
  Canada: 'America/Toronto',
  'Cocos Keeling Islands': 'Indian/Cocos',
  'DR Congo': 'Africa/Kinshasa',
  'Central African Republic': 'Africa/Bangui',
  Congo: 'Africa/Brazzaville',
  Switzerland: 'Europe/Zurich',
  'Ivory Coast': 'Africa/Abidjan',
  'Cook Islands': 'Pacific/Rarotonga',
  Colombia: 'America/Bogota',
  'Costa Rica': 'America/Costa_Rica',
  Cuba: 'America/Havana',
  'Cape Verde': 'Atlantic/Cape_Verde',
  Curacao: 'America/Curacao',
  'Christmas Island': 'Indian/Christmas',
  Cyprus: 'Asia/Nicosia',
  Czechia: 'Europe/Prague',
  Djibouti: 'Africa/Djibouti',
  Denmark: 'Europe/Copenhagen',
  Dominica: 'America/Dominica',
  'Dominican Republic': 'America/Santo_Domingo',
  Algeria: 'Africa/Algiers',
  Ecuador: 'America/Guayaquil',
  Estonia: 'Europe/Tallinn',
  Egypt: 'Africa/Cairo',
  'Western Sahara': 'Africa/El_Aaiun',
  Eritrea: 'Africa/Asmara',
  Ethiopia: 'Africa/Addis_Ababa',
  Europe: 'Europe/Brussels',
  Finland: 'Europe/Helsinki',
  Fiji: 'Pacific/Fiji',
  'Falkland Islands': 'Atlantic/Stanley',
  Micronesia: 'Pacific/Chuuk',
  'Faroe Islands': 'Atlantic/Faroe',
  Gabon: 'Africa/Libreville',
  Grenada: 'America/Grenada',
  Georgia: 'Asia/Tbilisi',
  'French Guiana': 'America/Cayenne',
  Guernsey: 'Europe/Guernsey',
  Ghana: 'Africa/Accra',
  Gibraltar: 'Europe/Gibraltar',
  Greenland: 'America/Godthab',
  Gambia: 'Africa/Banjul',
  Guinea: 'Africa/Conakry',
  Guadeloupe: 'America/Guadeloupe',
  'Equatorial Guinea': 'Africa/Malabo',
  Guatemala: 'America/Guatemala',
  Guam: 'Pacific/Guam',
  'Guinea-Bissau': 'Africa/Bissau',
  Guyana: 'America/Guyana',
  'Hong Kong': 'Asia/Hong_Kong',
  'Heard and McDonald Islands': 'Indian/Kerguelen',
  Honduras: 'America/Tegucigalpa',
  Croatia: 'Europe/Zagreb',
  Haiti: 'America/Port-au-Prince',
  Hungary: 'Europe/Budapest',
  International: 'UTC',
  Israel: 'Asia/Jerusalem',
  'Isle of Man': 'Europe/Isle_of_Man',
  'British Indian Ocean Territory': 'Indian/Chagos',
  Iraq: 'Asia/Baghdad',
  Iran: 'Asia/Tehran',
  Ireland: 'Europe/Dublin',
  Jersey: 'Europe/Jersey',
  Jamaica: 'America/Jamaica',
  Jordan: 'Asia/Amman',
  Kenya: 'Africa/Nairobi',
  Kyrgyzstan: 'Asia/Bishkek',
  Cambodia: 'Asia/Phnom_Penh',
  Kiribati: 'Pacific/Tarawa',
  Comoros: 'Indian/Comoro',
  'Saint Kitts and Nevis': 'America/St_Kitts',
  'North Korea': 'Asia/Pyongyang',
  'South Korea': 'Asia/Seoul',
  Kuwait: 'Asia/Kuwait',
  'Cayman Islands': 'America/Cayman',
  Kazakhstan: 'Asia/Almaty',
  Laos: 'Asia/Vientiane',
  Lebanon: 'Asia/Beirut',
  'Saint Lucia': 'America/St_Lucia',
  Liechtenstein: 'Europe/Vaduz',
  'Sri Lanka': 'Asia/Colombo',
  Liberia: 'Africa/Monrovia',
  Lesotho: 'Africa/Maseru',
  Lithuania: 'Europe/Vilnius',
  Luxembourg: 'Europe/Luxembourg',
  Latvia: 'Europe/Riga',
  Libya: 'Africa/Tripoli',
  Morocco: 'Africa/Casablanca',
  Monaco: 'Europe/Monaco',
  Moldova: 'Europe/Chisinau',
  Montenegro: 'Europe/Podgorica',
  'Saint-Martin': 'America/Marigot',
  Madagascar: 'Indian/Antananarivo',
  'Marshall Islands': 'Pacific/Majuro',
  Mixed: 'UTC',
  Macedonia: 'Europe/Skopje',
  Mali: 'Africa/Bamako',
  Myanmar: 'Asia/Yangon',
  Macau: 'Asia/Macau',
  'Northern Mariana Islands': 'Pacific/Saipan',
  Martinique: 'America/Martinique',
  Mauritania: 'Africa/Nouakchott',
  Montserrat: 'America/Montserrat',
  Malta: 'Europe/Malta',
  Mauritius: 'Indian/Mauritius',
  Maldives: 'Indian/Maldives',
  Malawi: 'Africa/Blantyre',
  Malaysia: 'Asia/Kuala_Lumpur',
  Mozambique: 'Africa/Maputo',
  'Northern Ireland': 'Europe/Belfast',
  Namibia: 'Africa/Windhoek',
  'New Caledonia': 'Pacific/Noumea',
  Niger: 'Africa/Niamey',
  'Norfolk Island': 'Pacific/Norfolk',
  Nigeria: 'Africa/Lagos',
  Nicaragua: 'America/Managua',
  'The Netherlands': 'Europe/Amsterdam',
  Norway: 'Europe/Oslo',
  Nepal: 'Asia/Kathmandu',
  Nauru: 'Pacific/Nauru',
  Niue: 'Pacific/Niue',
  'New Zealand': 'Pacific/Auckland',
  Oman: 'Asia/Muscat',
  Panama: 'America/Panama',
  Peru: 'America/Lima',
  'French Polynesia': 'Pacific/Tahiti',
  'Papua New Guinea': 'Pacific/Port_Moresby',
  Philippines: 'Asia/Manila',
  Pakistan: 'Asia/Karachi',
  Poland: 'Europe/Warsaw',
  Pitcairn: 'Pacific/Pitcairn',
  'Puerto Rico': 'America/Puerto_Rico',
  Palestine: 'Asia/Gaza',
  Palau: 'Pacific/Palau',
  Paraguay: 'America/Asuncion',
  Qatar: 'Asia/Qatar',
  Reunion: 'Indian/Reunion',
  Romania: 'Europe/Bucharest',
  Serbia: 'Europe/Belgrade',
  Russia: 'Europe/Moscow',
  Rwanda: 'Africa/Kigali',
  'Saudi Arabia': 'Asia/Riyadh',
  'Solomon Islands': 'Pacific/Guadalcanal',
  Seychelles: 'Indian/Mahe',
  Sudan: 'Africa/Khartoum',
  Sweden: 'Europe/Stockholm',
  Singapore: 'Asia/Singapore',
  'Saint Helena': 'Atlantic/St_Helena',
  Slovenia: 'Europe/Ljubljana',
  Svalbard: 'Arctic/Longyearbyen',
  Slovakia: 'Europe/Bratislava',
  'Sierra Leone': 'Africa/Freetown',
  'San Marino': 'Europe/San_Marino',
  Senegal: 'Africa/Dakar',
  Somalia: 'Africa/Mogadishu',
  Suriname: 'America/Paramaribo',
  'South Sudan': 'Africa/Juba',
  'Sao Tome and Principe': 'Africa/Sao_Tome',
  'El Salvador': 'America/El_Salvador',
  Syria: 'Asia/Damascus',
  Swaziland: 'Africa/Mbabane',
  'Turks and Caicos Islands': 'America/Grand_Turk',
  Chad: 'Africa/Ndjamena',
  'French Southern Territories': 'Indian/Kerguelen',
  Togo: 'Africa/Lome',
  Thailand: 'Asia/Bangkok',
  Tajikistan: 'Asia/Dushanbe',
  Tokelau: 'Pacific/Fakaofo',
  'East Timor': 'Asia/Dili',
  Turkmenistan: 'Asia/Ashgabat',
  Tunisia: 'Africa/Tunis',
  Tonga: 'Pacific/Tongatapu',
  Turkey: 'Europe/Istanbul',
  'Trinidad and Tobago': 'America/Port_of_Spain',
  Tuvalu: 'Pacific/Funafuti',
  Taiwan: 'Asia/Taipei',
  Tanzania: 'Africa/Dar_es_Salaam',
  Ukraine: 'Europe/Kiev',
  Uganda: 'Africa/Kampala',
  'United States': 'America/New_York',
  Uruguay: 'America/Montevideo',
  Uzbekistan: 'Asia/Tashkent',
  Vatican: 'Europe/Vatican',
  'Saint Vincent and the Grenadines': 'America/St_Vincent',
  Venezuela: 'America/Caracas',
  'British Virgin Islands': 'America/Tortola',
  'United States Virgin Islands': 'America/St_Thomas',
  Vanuatu: 'Pacific/Efate',
  Worldwide: 'UTC',
  World: 'UTC',
  Wales: 'Europe/London',
  'Wallis and Futuna Islands': 'Pacific/Wallis',
  Samoa: 'Pacific/Apia',
  Kosovo: 'Europe/Belgrade',
  Yemen: 'Asia/Aden',
  Mayotte: 'Indian/Mayotte',
  'South Africa': 'Africa/Johannesburg',
  Zambia: 'Africa/Lusaka',
  Zimbabwe: 'Africa/Harare',
  Scotland: 'Europe/London',
  'United Kingdom': 'Europe/London',
};
