export const LEAGUE_NAME_ALIASES: Record<string, string> = {
  // Liga original já existente
  jupilerproleague: 'proleague',
  belgianproleague: 'proleague',
  eredivisie: 'eredivisie',
  dutcheredivisie: 'eredivisie',
  premierleague: 'premierleague',
  englishpremierleague: 'premierleague',
  premiership: 'scottishpremiership',
  scottishpremiership: 'scottishpremiership',
  scottishpremierleague: 'scottishpremiership',

  // Discrepâncias principais encontradas
  'english league championship': 'championship',
  championship: 'championship',
  'english league 1': 'leagueone',
  leagueone: 'leagueone',
  'english league 2': 'leaguetwo',
  leaguetwo: 'leaguetwo',
  'scottish championship': 'scottishchampionship',
  'scottish league 1': 'scottishleagueone',
  'scottish league 2': 'scottishleaguetwo',
  'german bundesliga': 'bundesliga',
  bundesliga: 'bundesliga',
  'italian serie a': 'seriea',
  'serie a': 'seriea',
  'french ligue 1': 'ligue1',
  'ligue 1': 'ligue1',
  'spanish la liga': 'laliga',
  'la liga': 'laliga',
  'dutch eredivisie': 'eredivisie',
  'belgian pro league': 'proleague',
  'turkish super lig': 'superlig',
  'super lig': 'superlig',
  'portuguese primeira liga': 'primeiraliga',
  'primeira liga': 'primeiraliga',
  'american major league soccer': 'mls',
  mls: 'mls',
  'swedish allsvenskan': 'allsvenskan',
  allsvenskan: 'allsvenskan',
  'mexican primera league': 'ligamx',
  'liga mx': 'ligamx',
  'brazilian serie a': 'seriea',
  'australian a-league': 'aleague',
  'a-league': 'aleague',
  'norwegian eliteserien': 'eliteserien',
  eliteserien: 'eliteserien',
  'chinese super league': 'chinesesuperleague',
  'italian serie b': 'serieb',
  'serie b': 'serieb',
  'german 2. bundesliga': '2bundesliga',
  '2. bundesliga': '2bundesliga',
  'spanish la liga 2': 'laliga2',
  'la liga 2': 'laliga2',
  'french ligue 2': 'ligue2',
  'ligue 2': 'ligue2',
  'swedish superettan': 'superettan',
  superettan: 'superettan',
  'brazilian serie b': 'serieb',
  'argentinian primera division': 'primera division',
  'polish ekstraklasa': 'ekstraklasa',
  ekstraklasa: 'ekstraklasa',
  'fifa world cup': 'worldcup',
  'world cup': 'worldcup',
  'uruguayan primera division': 'primera division',
  'welsh premier league': 'welshpremierleague',
  'cymru premier': 'welshpremierleague',
  'uefa champions league': 'championsleague',
  'champions league': 'championsleague',
  'uefa europa league': 'europaleague',
  'europa league': 'europaleague',
  'fa cup': 'facup',
  'copa del rey': 'copadelrey',
  'coupe de france': 'coupedefrance',
  'dfb-pokal': 'dfbpokal',
  'uefa nations league': 'nationsleague',
  'african cup of nations': 'africancupofnations',
  afcon: 'africancupofnations',
  'colombia categoría primera a': 'ligadimayor',
  'confederations cup': 'confederationscup',
  'copa america': 'copaamerica',
  'copa argentina': 'copaargentina',
  'copa libertadores': 'copalibertadores',
  'uefa european championships': 'euro',
  euro: 'euro',
  'fifa club world cup': 'clubworldcup',
  'coupe de la ligue': 'coupedelaligue',
  'international champions cup': 'internationalchampionscup',
  'coppa italia': 'coppaitalia',
  'supercoppa italiana': 'supercoppaitaliana',
  'taca de liga': 'tacadeliga',
  'taca de portugal': 'tacadeportugal',
  'supercopa de espana': 'supercopadeespana',
  'uefa super cup': 'uefasupercup',
  'american nwsl': 'nwsl',
  nwsl: 'nwsl',
  'european cup': 'europeancup',
  'uefa cup': 'uefacup',
  'international friendlies': 'friendlies',
  friendlies: 'friendlies',
  'fifa womens world cup': 'womensworldcup',
  'club friendlies': 'clubfriendlies',
  'efl cup': 'eflcup',
  'carabao cup': 'eflcup',
  'fa community shield': 'communityshield',
  'english national league': 'nationalleague',
  'argentinian primera b nacional': 'primera b nacional',
  'albanian superliga': 'superliga',
  'andorran 1a divisió': '1adivisio',
  'armenian premier league': 'armenianpremierleague',
  'austrian bundesliga': 'austrianbundesliga',
  'belarus vyscha liga': 'belarusianpremierleague',
  'belgian first division b': 'challengerproleague',
  'bosnian premier liga': 'premierliga',
  'brazilian serie c': 'seriec',
  'bulgarian first league': 'firstleague',
  'chile primera division': 'primera division',
  'china league one': 'leagueone',
  'croatian first football league': 'prvahnl',
  'cypriot first division': 'firstdivision',
  'czech first league': 'firstleague',
  'danish 2nd division': '2nddivision',
  'japanese j1 league': 'j1league',
  'j1 league': 'j1league',
  'estonian meistriliiga': 'meistriliiga',
  'faroe islands premier league': 'faroeislandspremierleague',
  'finnish veikkausliiga': 'veikkausliiga',
  'french championnat national': 'championnatnational',
  'georgian erovnuli liga': 'erovnuliliga',
  'germany liga 3': 'liga3',
  'greek super league 2': 'superleague2',
  'dutch eerste divisie': 'eerstedivisie',
  'icelandic úrvalsdeild karla': 'urvalsdeild',
  'irish premier division': 'premierdivision',
  'israeli premier league': 'premierleague',
  'kazakhstan premier league': 'premierleague',
  'latvian higher league': 'higherleague',
  'lithuanian a lyga': 'alyga',
  'macedonian first league': 'firstleague',
  'maltese premier league': 'premierleague',
  'mexican liga de expansión mx': 'ligaexpansionmx',
  'moldovan national division': 'nationaldivision',
  'montenegrin first league': 'firstleague',
  'moroccan botola 2': 'botola2',
  'northern irish premiership': 'premiership',
  'polish i liga': 'iliga',
  'portuguese ligapro': 'ligapro',
  'qatar stars league': 'starsleague',
  'romanian liga ii': 'liga2',
  'russian football national league': 'nationalleague',
  'san-marino campionato': 'campionato',
  'saudi-arabian pro league': 'proleague',
  'serbian super liga': 'superliga',
  'slovak first football league': 'firstleague',
  'swiss super league': 'superleague',
  'turkish 1 lig': '1lig',
  'ukrainian first league': 'firstleague',
  'uae pro league': 'proleague',
  'turkish 2 lig': '2lig',
  'english national league north': 'nationalleaguenorth',
  'english national league south': 'nationalleaguesouth',
  'danish 1st division': '1stdivision',
  'american usl championship': 'uslchampionship',
  'bolivian primera división': 'primera division',
  'ecuadorian serie a': 'seriea',
  'paraguayan primera division': 'primera division',
  'peruvian primera division': 'primera division',
  'south korean k league 1': 'kleague1',
  'k league 1': 'kleague1',
  'hungarian nb i': 'nbi',
  'romanian liga i': 'ligai',
  'slovenian 1. snl': '1snl',
  'azerbaijani premier league': 'premierleague',
  'luxembourg national division': 'nationaldivision',
  'german regionalliga nord': 'regionalliganord',
  'swiss challenge league': 'challengeleague',
  'afc champions league elite': 'afcchampionsleague',
  'caf champions league': 'cafchampionsleague',
  'concacaf champions cup': 'concacafchampionscup',
  'scottish fa cup': 'facup',
  'copa sudamericana': 'copasudamericana',
  'copa do brasil': 'copadobrasil',
  'concacaf central american cup': 'centralamericancup',
  'iranian azadegan league': 'azadeganleague',
  'iranian persian gulf pro league': 'persiangulfproleague',
  'thai premier league': 'thaileague',
  'thai league 1': 'thaileague1',
  'thai league 2': 'thaileague2',
  'kenyan premier league': 'premierleague',
  'algerian ligue 1': 'ligue1',
  'senegal ligue 1': 'ligue1',
  'northern irish championship': 'championship',
  'svenska cupen': 'svenskacupen',
  'irish first division': 'firstdivision',
  'fa trophy': 'fatrophy',
  'malaysian premier league': 'premierleague',
  'indonesian super league': 'superleague',
  'indian super league': 'superleague',
  'malaysian super league': 'superleague',
  'cambodia c-league': 'cleague',
  'uzbekistan super league': 'superleague',
  'singapore premier league': 'premierleague',
  'austrian erste liga': 'ersteliga',
  'indian i-league': 'ileague',
  'south african premier soccer league': 'premiersoccerleague',
  'vietnamese v.league 1': 'vleague1',
  'afc champions league two': 'afcchampionsleague',
  'australian a-league women': 'aleaguewomen',
  'nicaragua primera division': 'primera division',
  'tajikistan vysshaya liga': 'vysshayaliga',
  'belarusian first league': 'firstleague',
  'belarus coppa': 'coppa',
  'new-zealand football championship': 'footballchampionship',
  'costa-rica liga fpd': 'ligafpd',
  'el salvador primera division': 'primera division',
  'guatemala liga nacional': 'liganacional',
  'honduras liga nacional de futbol': 'liganacional',
  'panama liga panamena de futbol': 'ligapanamena',
  'canadian premier league': 'premierleague',
  'indian i-league 2nd division': 'ileague2',
  'south korean k league 2': 'kleague2',
  'k league 2': 'kleague2',
  'kuwait premier league': 'premierleague',
  'japanese j2 league': 'j2league',
  'j2 league': 'j2league',
  'hong-kong premier league': 'premierleague',
  'bahrain premier league': 'premierleague',
  'nigerian npfl': 'npfl',
  'tunisian ligue 1': 'ligue1',
  'egyptian premier league': 'premierleague',
  'swedish division 1 south': 'division1south',
  'efl trophy': 'efltrophy',
  'english womens super league': 'womenssuperleague',
  'uefa womens euro': 'womenseuro',
  'afc asian cup': 'asiancup',
  'ofc nations cup': 'nationscup',
  'concacaf gold cup': 'goldcup',
  'spanish segunda división b group 5': 'segunda division b',
  'fa womens league cup': 'womensleaguecup',
  'scottish league cup': 'leaguecup',
  'uefa womens champions league': 'womenschampionsleague',
  'chile primera b': 'primera b',
  'paraguayan división intermedia': 'divisionintermedia',
  'french trophée des champions': 'tropheedeschampions',
  'dutch knvb cup': 'knvbcup',
  'german super cup': 'supercup',
  'andorran segona divisió': 'segona divisio',
  'andorran cup': 'cup',
  'icelandic 1 deild karla': '1deild',
  'albanian kategoria e parë': 'kategoria e pare',
  'armenian first league': 'firstleague',
  'armenian cup': 'cup',
  'bolivian nacional b copa simón bolívar': 'nacional b',
  'bosnian first league': 'firstleague',
  'bosnian first league of srpska': 'firstleague',
  'bulgarian second league': 'secondleague',
  'azerbaijan first division': 'firstdivision',
  'azerbaijan cup': 'cup',
  'colombian categoría primera b': 'categoria primera b',
  'croatian druga hnl': 'druga hnl',
  'cypriot second division': 'seconddivision',
  'czech national football league': 'nationalleague',
  'dr congo ligue 1': 'ligue1',
  'dominican ldf': 'ldf',
  'ecuadorian serie b': 'serieb',
  'estonian esiliiga': 'esiliiga',
  'ethiopian premier league': 'premierleague',
  'turkish cup': 'cup',
  'faroe islands 1. deild': '1deild',
  'fijian premier league': 'premierleague',
  'finnish ykkönen': 'ykkonen',
  'gibraltarian national league': 'nationalleague',
  'hungarian nb ii': 'nbii',
  'israeli liga leumit': 'liga leumit',
  'japanese j3 league': 'j3league',
  'j3 league': 'j3league',
  'kosovan superleague': 'superleague',
  'kyrgyz premier league': 'premierleague',
  'lao premier league': 'premierleague',
  'emir of qatar cup': 'emirofqatarcup',
  'liechtenstein cup': 'cup',
  'georgian erovnuli liga 2': 'erovnuli liga 2',
  'ghanaian premier league': 'premierleague',
  'english womens super league 2': 'womenssuperleague2',
  'kuwait division 1': 'division1',
  'vietnam v.league 2': 'vleague2',
  'argentina primera b metropolitana': 'primera b metropolitana',
  'portugal liga 3': 'liga3',
  'usa nisa': 'nisa',
  'denmark 3 division': '3division',
  'netherlands derde divisie saturday': 'derdedivisie',
  'netherlands derde divisie sunday': 'derdedivisie',
  'angolan girabola': 'girabola',
  'aruban division di honor': 'division di honor',
  'benin championnat national': 'championnat national',
  'bermuda premier league': 'premierleague',
  'botswana premier league': 'premierleague',
  'burkina faso 1ere division': '1ere division',
  'burundi ligue a': 'ligue a',
  'eswatini premier league': 'premierleague',
  'gambia gfa league': 'gfa league',
  'guadeloupe division dhonneur': 'division dhonneur',
  'guinea ligue 1': 'ligue1',
  'ivory coast ligue 1': 'ligue1',
  'lebanon premier league': 'premierleague',
  'liberian lfa first division': 'firstdivision',
  'libyan premier league': 'premierleague',
  'maldives dhivehi premier league': 'dhivehi premierleague',
  'mauritania premier league': 'premierleague',
  'mongolian premier league': 'premierleague',
  'nepalese a division': 'adivision',
  'oman professional league': 'professionalleague',
  'pakistan premier league': 'premierleague',
  'palestinian west bank premier league': 'westbank premierleague',
  'rwandan national soccer league': 'nationalsoccerleague',
  'somali premier league': 'premierleague',
  'sudani premier league': 'premierleague',
  'syrian premier league': 'premierleague',
  'turkmenistan yokary liga': 'yokary liga',
  'ugandan premier league': 'premierleague',
  'zimbabwe premier soccer league': 'premiersoccerleague',
  'shebelieves cup': 'shebelievescup',
  'mls next pro': 'mlsnextpro',
  'concacaf nations league': 'nationsleague',
  'leagues cup': 'leaguescup',
  'china league two': 'leaguetwo',
  'slovenian 2 snl': '2snl',
  'slovakian 2 liga': '2liga',
  'welsh cymru north-south': 'cymru north-south',
  'austrian regionalliga west': 'regionalligawest',
  'austrian regionalliga ost': 'regionalligaost',
  'austrian regionalliga mitte': 'regionalligamitte',
  'swiss promotion league': 'promotionleague',
  'english southern premier league central division':
    'southernpremierleaguecentral',
  'chile segunda división': 'segunda division',
  'afc challenge league': 'challengeleague',
  'swiss cup': 'cup',
  'usl super league': 'uslsuperleague',
  'copa paraguay': 'copaparaguay',
  'world cup qualifying afc': 'worldcupqualifying',
  'world cup qualifying caf': 'worldcupqualifying',
  'world cup qualifying conmebol': 'worldcupqualifying',
  'world cup qualifying concacaf': 'worldcupqualifying',
  'world cup qualifying ofc': 'worldcupqualifying',
  'world cup qualifying uefa': 'worldcupqualifying',
  'uefa european championships qualifying': 'euroqualifying',
  'african cup of nations qualifying': 'afconqualifying',
  'afc asian cup qualifying': 'asiancupqualifying',
  'concacaf gold cup qualifying': 'goldcupqualifying',
  'china fa cup': 'facup',
  'copa auf uruguay': 'copauruguay',
  'philippines football league': 'footballleague',
  'polish ii liga': 'iiliga',
  'australian championship': 'championship',
  'concacaf w gold cup': 'wgoldcup',
  'supercopa de espana femenina': 'supercopadeespanafemenina',
  'fa womens challenge cup': 'womenschallengecup',
  'finnish ykkösliiga': 'ykkösliiga',
  'norwegian cupen': 'cup',
  'korea cup': 'cup',
  'copa ecuador': 'copaecuador',
  'japan emperors cup': 'emperorscup',
  'irish fai cup': 'faicup',
  'korean k3 league': 'k3league',
  'concacaf w champions cup': 'wchampionscup',
  'fifa u20 world cup': 'u20worldcup',
  'english premier league summer series': 'summerseries',
  'emirates cup': 'emiratescup',
  'saudi king cup': 'kingcup',
  'saudi super cup': 'supercup',
  'usl cup': 'cup',
  'kazakhstan first league': 'firstleague',
  'kazakhstan cup': 'cup',
  'copa america femenina': 'copaamericafemenina',
  'lithuanian i lyga': 'ilyga',
  'lithuanian football cup': 'cup',
  'lithuanian supercup': 'supercup',
  'venezuelan segunda division': 'segunda division',
  'copa venezuela': 'copavenezuela',
  'supercopa de venezuela': 'supercopavenezuela',
  'mexican campeon de campeones': 'campeondecampeones',
  'argentinian supercopa internacional': 'supercopainternacional',
  'argentinian trofeo de campeones': 'trofeodecampeones',
  'recopa sudamericana': 'recopasudamericana',
  'copa paulista': 'copapaulista',
  'brazilian copa do nordeste': 'copadonordeste',
  'asean club championship': 'aseanclubchampionship',
  'brazilian copa verde': 'copaverde',
  'brazilian campeonato acreano': 'acreano',
  'brazilian campeonato alagoano': 'alagoano',
  'brazilian campeonato amapaense': 'amapaense',
  'brazilian campeonato amazonense': 'amazonense',
  'cafa nations cup': 'cafanationscup',
  'brazilian campeonato baiano': 'baiano',
  'brazilian campeonato brasiliense': 'brasiliense',
  'brazilian campeonato capixaba': 'capixaba',
  'brazilian campeonato catarinense': 'catarinense',
  'brazilian campeonato carioca': 'carioca',
  'brazilian campeonato cearense': 'cearense',
  'brazilian campeonato gaucho': 'gaucho',
  'brazilian copa fgf': 'copafgf',
  'fifa intercontinental cup': 'intercontinentalcup',
  'supercopa de chile': 'supercopachile',
  'uefa womens europa cup': 'womenseuropacup',
  'afc womens champions league': 'womenschampionsleague',
  'concacaf caribbean cup': 'caribbeancup',
  'spanish copa federacion': 'copafederacion',
  'copa libertadores femenina': 'libertadoresfemenina',
  'concacaf womens olympic qualifying tournament': 'olympicqualifying',
  'campeonato de portugal serie a': 'campeonatoportugalseriea',
  'campeonato de portugal serie b': 'campeonatoportugalserieb',
  'campeonato de portugal serie c': 'campeonatoportugalseriec',
  'campeonato de portugal serie d': 'campeonatoportugalseried',
  'concacaf series': 'concacafseries',
  'norwegian second division group 1': 'seconddivision',
  'norwegian second division group 2': 'seconddivision',
  'brazilian campeonato goiano': 'goiano',
  'brazilian campeonato maranhense': 'maranhense',
  'brazilian campeonato matogrossense': 'matogrossense',
  'brazilian campeonato mineiro': 'mineiro',
  'brazilian campeonato paraense': 'paraense',
  'brazilian campeonato paraibano': 'paraibano',
  'brazilian campeonato paranaense': 'paranaense',
  'brazilian campeonato paulista': 'paulista',
  'brazilian campeonato pernambucano': 'pernambucano',
  'brazilian campeonato piauiense': 'piauiense',
  'brazilian campeonato potiguar': 'potiguar',
  'brazilian campeonato rondoniense': 'rondoniense',
  'brazilian campeonato roraimense': 'roraimense',
  'brazilian campeonato sergipano': 'sergipano',
  'brazilian campeonato sulmatogrossense': 'sulmatogrossense',
  'brazilian campeonato tocantinense': 'tocantinense',
  'brazilian supercopa rei': 'supercoparei',
  'french national 3 group a': 'national3',
  'french national 3 group b': 'national3',
  'french national 3 group c': 'national3',
  'french national 3 group d': 'national3',
  'french national 3 group e': 'national3',
  'french national 3 group f': 'national3',
  'french national 3 group g': 'national3',
  'french national 3 group h': 'national3',

  // Duplicatas que podem aparecer em formatos diferentes
  'english league one': 'leagueone',
  'english league two': 'leaguetwo',
  'english championship': 'championship',
  'spanish segunda division': 'laliga2',
  'french division 1': 'ligue1',
  'italian first division': 'seriea',
  'german first division': 'bundesliga',
  'dutch first division': 'eredivisie',
  'portuguese first division': 'primeiraliga',
  'scottish first division': 'scottishpremiership',
  'belgian first division a': 'proleague',
  'turkish first division': 'superlig',
  'greek first division': 'superleague',
  'russian first division': 'premierleague',
  'ukrainian first division': 'premierleague',
  'polish first division': 'ekstraklasa',
  'czech first division': 'firstleague',
  'swiss first division': 'superleague',
  'austrian first division': 'austrianbundesliga',
  'danish first division': 'superliga',
  'norwegian first division': 'eliteserien',
  'swedish first division': 'allsvenskan',
  'finnish first division': 'veikkausliiga',
  'icelandic first division': 'urvalsdeild',
  'croatian first division': 'prvahnl',
  'serbian first division': 'superliga',
  'romanian first division': 'ligai',
  'bulgarian first division': 'firstleague',
  'slovak first division': 'firstleague',
  'slovenian first division': '1snl',
  'hungarian first division': 'nbi',
  'georgian first division': 'erovnuliliga',
  'azerbaijani first division': 'premierleague',
  'kazakh first division': 'premierleague',
  'belarusian first division': 'premierleague',
  'moldovan first division': 'nationaldivision',
  'latvian first division': 'higherleague',
  'lithuanian first division': 'alyga',
  'estonian first division': 'meistriliiga',
  'faroe islands first division': 'faroeislandspremierleague',
  'maltese first division': 'premierleague',
  'luxembourgish first division': 'nationaldivision',
  'andorran first division': '1adivisio',
  'san marino first division': 'campionato',
  'montenegrin first division': 'firstleague',
  'kosovan first division': 'superleague',
  'albanian first division': 'superliga',
  'bosnian first division': 'premierliga',
  'macedonian first division': 'firstleague',
  'israeli first division': 'premierleague',
  'armenian first division': 'armenianpremierleague',
};
